2023-08-27 19:28:52,271 [INFO] root tankworker.py:153	Log file created
2023-08-27 19:28:52,272 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2023-08-27 19:28:52,272 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2023-08-27 19:28:52,273 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2023-08-27 19:28:52,301 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2023-08-27_19-28-52.131820
2023-08-27 19:28:52,305 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2023-08-27 19:28:52,306 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2023-08-27 19:28:52,308 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2023-08-27 19:28:52,309 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2023-08-27 19:28:52,311 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2023-08-27 19:28:52,312 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2023-08-27 19:28:52,313 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2023-08-27 19:28:52,314 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2023-08-27 19:28:52,320 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2023-08-27 19:28:52,321 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2023-08-27 19:28:52,322 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2023-08-27 19:28:52,322 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2023-08-27 19:28:52,323 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2023-08-27 19:28:52,324 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2023-08-27 19:28:52,325 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2023-08-27 19:28:52,325 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2023-08-27 19:28:52,326 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2023-08-27 19:28:52,327 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2023-08-27 19:28:52,358 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.2 and port 8080
2023-08-27 19:28:52,370 [INFO] yandextank.plugins.Phantom.utils utils.py:277	Resolved host.docker.internal into 192.168.65.2:8080
2023-08-27 19:28:52,371 [INFO] yandextank.stepper.main main.py:197	Configuring StepperWrapper...
2023-08-27 19:28:52,374 [INFO] yandextank.stepper.main main.py:336	Making stpd-file: /var/loadtest/logs/_92b860d5b1b303c28f25be687787e189.stpd
2023-08-27 19:28:52,379 [INFO] yandextank.stepper.config config.py:126	Using UriStyleGenerator ammo reader
2023-08-27 19:28:52,611 [INFO] yandextank.core.tankcore tankcore.py:268	Preparing test...
2023-08-27 19:28:52,694 [INFO] yandextank.common.interfaces plugin.py:38	Checking tank resources...
2023-08-27 19:28:52,766 [INFO] root plugin.py:585	Using OVERLOAD backend
2023-08-27 19:28:52,770 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:703	Read authentication token from token.txt, token length is 32 bytes
2023-08-27 19:28:52,814 [INFO] yandextank.plugins.DataUploader.client client.py:81	Proxy not set
2023-08-27 19:28:52,815 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:728	Detected target: host.docker.internal
2023-08-27 19:28:53,214 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:877	Job created: 636995
2023-08-27 19:28:53,319 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:547	Locking targets: ['host.docker.internal']
2023-08-27 19:28:53,323 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:549	Locked targets: ['host.docker.internal']
2023-08-27 19:28:53,711 [INFO] yandextank.core.tankcore tankcore.py:278	Starting test...
2023-08-27 19:28:53,725 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:65	using verbose histogram
2023-08-27 19:28:53,745 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_autostop required 0.000011 seconds to start
2023-08-27 19:28:53,746 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_console required 0.000007 seconds to start
2023-08-27 19:28:53,747 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_json_report required 0.000006 seconds to start
2023-08-27 19:28:53,768 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_phantom required 0.020471 seconds to start
2023-08-27 19:28:53,769 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_rcheck required 0.000015 seconds to start
2023-08-27 19:28:53,770 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_shellexec required 0.000027 seconds to start
2023-08-27 19:28:53,771 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_rcassert required 0.000067 seconds to start
2023-08-27 19:28:53,774 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:456	Status sender thread started
2023-08-27 19:28:53,777 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:475	Data Uploader thread started
2023-08-27 19:28:53,780 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:475	Monitoring Uploader thread started
2023-08-27 19:28:53,780 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:360	Web link: https://overload.yandex.net/636995
2023-08-27 19:28:54,040 [INFO] yandextank.core.tankcore tankcore.py:285	Plugin plugin_overload required 0.267729 seconds to start
2023-08-27 19:28:54,042 [INFO] yandextank.core.tankcore tankcore.py:294	Waiting for test to finish...
2023-08-27 19:28:54,043 [INFO] yandextank.core.tankcore tankcore.py:295	Artifacts dir: /var/loadtest/logs/2023-08-27_19-28-52.131820
2023-08-27 19:29:53,974 [INFO] yandextank.plugins.Phantom.plugin plugin.py:155	Phantom done its work with exit code: 0
2023-08-27 19:29:53,976 [INFO] yandextank.core.tankcore tankcore.py:331	Finishing test...
2023-08-27 19:29:53,978 [INFO] yandextank.core.tankcore tankcore.py:334	Stopping load generator and aggregator
2023-08-27 19:29:53,979 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:126	Closing stats reader
2023-08-27 19:29:53,980 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:129	Waiting for gun drain to finish
2023-08-27 19:29:54,844 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:131	Waiting for stats drain to finish
2023-08-27 19:29:54,846 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:133	Collecting remaining data
2023-08-27 19:29:54,854 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:111	Timestamps without stats:
2023-08-27 19:29:54,856 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:113	1693164592
2023-08-27 19:29:54,866 [INFO] yandextank.aggregator.tank_aggregator tank_aggregator.py:113	1693164593
2023-08-27 19:29:54,873 [INFO] yandextank.core.tankcore tankcore.py:338	Stopping monitoring
2023-08-27 19:30:12,985 [WARNING] yandextank.plugins.DataUploader.client client.py:218	Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'unexpected eof while reading')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', '', 'unexpected eof while reading')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='overload.yandex.net', port=443): Max retries exceeded with url: /api/job/636995/configinitial.txt?api_token=f0abbbaf79844ac396743534e5fc5c73 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'unexpected eof while reading')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/DataUploader/client.py", line 215, in __make_api_request
    response = self.__send_single_request(request, next(ids), trace=trace)
  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/DataUploader/client.py", line 153, in __send_single_request
    resp = self.session.send(p, timeout=self.connection_timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='overload.yandex.net', port=443): Max retries exceeded with url: /api/job/636995/configinitial.txt?api_token=f0abbbaf79844ac396743534e5fc5c73 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'unexpected eof while reading')])")))

2023-08-27 19:30:12,990 [WARNING] yandextank.plugins.DataUploader.client client.py:222	Network error, will retry in 10s...
2023-08-27 19:30:23,546 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:540	Unlocking targets: ['host.docker.internal']
2023-08-27 19:30:23,553 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:542	host.docker.internal
2023-08-27 19:30:23,556 [INFO] yandextank.core.tankcore tankcore.py:361	Post-processing test...
2023-08-27 19:30:23,563 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:412	Waiting for sender threads to join.
2023-08-27 19:30:23,564 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:480	Monitoring Uploader queue returned None
2023-08-27 19:30:23,565 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:480	Data Uploader queue returned None
2023-08-27 19:30:23,568 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:500	Closing Monitoring Uploader thread
2023-08-27 19:30:23,569 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:500	Closing Data Uploader thread
2023-08-27 19:30:23,573 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:418	Web link: https://overload.yandex.net/636995
2023-08-27 19:30:23,795 [INFO] yandextank.common.util util.py:816	Trying to clean up
2023-08-27 19:30:23,801 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_autostop
2023-08-27 19:30:23,805 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_console
2023-08-27 19:30:23,807 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_json_report
2023-08-27 19:30:23,809 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_phantom
2023-08-27 19:30:23,811 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_rcheck
2023-08-27 19:30:23,812 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_shellexec
2023-08-27 19:30:23,814 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_rcassert
2023-08-27 19:30:23,816 [INFO] yandextank.core.tankcore tankcore.py:562	Cleaning up plugin plugin_overload
2023-08-27 19:30:23,817 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:540	Unlocking targets: ['host.docker.internal']
2023-08-27 19:30:23,818 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:542	host.docker.internal
2023-08-27 19:30:23,943 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_ys_a9avl.lock
2023-08-27 19:30:23,970 [INFO] yandextank.plugins.DataUploader.plugin plugin.py:472	Closed Status sender thread
2023-08-27 19:30:23,973 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2023-08-27_19-28-52.131820
2023-08-27 19:30:23,975 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2023-08-27 19:30:23,977 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-28-52.131820/answ_85yq5gik.log
2023-08-27 19:30:23,979 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-28-52.131820/phout_v5nfjxyl.log
2023-08-27 19:30:23,981 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-28-52.131820/phantom_stat_6pbaoahp.log
2023-08-27 19:30:23,983 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-28-52.131820/phantom_2i8jso22.log
2023-08-27 19:30:23,985 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-28-52.131820/phantom_otambyoi.conf
2023-08-27 19:30:23,986 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-28-52.131820/phantom_stdout_stderr_5v3jqrd1.log
